
<?php

$isActive = Mage::getStoreConfig("clearsale_total/general/active");

if($isActive)
{
$apiKey = Mage::getStoreConfig("clearsale_total/general/key");
$password = Mage::getStoreConfig("clearsale_total/general/clientsecret");
$user = Mage::getStoreConfig("clearsale_total/general/clientid");
$environment =  Mage::getStoreConfig("clearsale_total/general/environment"); 

$obj = Mage::getModel('total/observer');

$authBO = Mage::getModel('total/auth_business_object');
$authResponse = $authBO->login($environment);
$token = "";

if($authResponse)
{
$token = $authResponse->Token->Value;
}
$interval = "4";
$script = "<script>";
$script .= "var apiKey = \"".$apiKey."\";";
$script .= "var loginToken = \"".$token."\";";
$script .= "var user = \"".$user."\";";
$script .= "var password = \"".$password."\";";
$script .= "var interval = ".$interval.";";
$script .= "var prefix = \"".$environment."\";";
$script .= "</script>";

echo $script;

$baseDir = Mage::getBaseUrl('js');

echo "<script src=\"". $baseDir ."/clearsale/total/Graphs/graph-data.js\" ></script>";
}
?>   

<?php 
if ($isActive) :
?>


   <div class="container">
            <div class="block-header">
                <h2>Dashboard</h2>

                <ul class="actions">
                    <li class="width: 200px">
                        <i class="md md-event"></i>TIME VIEW
                    </li>
                    <li>
                        <select id="ReportFilter">
                            <option value="1">Today</option>
                            <option value="2">Last Week</option>
                            <option value="3">Last Month</option>
                            <option value="4">Last Year</option>
                        </select>
			<i class=\"md md-signal-cellular-4-bar\"></i>
                    </li>
                </ul>

            </div>


            <div class="mini-charts">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <div class="mini-charts-item bgm-orange">
                            <div class="clearfix">
                                <div class="chart"><i class="md md-vertical-align-bottom"></i></div>
                                <div class="count">
                                    <small>SUBMITTED</small>
                                    <h2 id="Submited">Loading...</h2>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-4">
                        <div class="mini-charts-item bgm-lightgreen">
                            <div class="clearfix">
                                <div class="chart"><i class="md md-done-all"></i></div>
                                <div class="count">
                                    <small>APPROVAL RATE</small>
                                    <h2 id="ApprovalRate">Loading...</h2>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-6 col-md-4">
                        <div class="mini-charts-item bgm-cyan">
                            <div class="clearfix">
                                <div class="chart"><i class="md md-multitrack-audio"></i></div>
                                <div class="count">
                                    <small>IN ANALYSIS</small>
                                    <h2 id="InAnlaysis">Loading...</h2>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>


            <div class="dash-widgets">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h2>Approval</h2>
                            </div>

                            <div class="card-body card-padding">
                                <div id="approval-chart" class="flot-chart-pie"></div>
                                <div class="flc-donut"></div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3 col-sm-6">
                        <div class="card">
                            <div class="card-header">
                                <h2>Decline</h2>
                            </div>

                            <div class="card-body card-padding">
                                <div id="decline-chart" class="flot-chart-pie"></div>
                                <div class="flc-donut"></div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                <h2>SLA Description</h2>
                            </div>

                            <div class="card-body card-padding-sm">
                                <div id="description-chart" class="flot-chart"></div>
                                <div class="flc-bar"></div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

            <div class="row bgm-white" style="margin:0 0px 50px 0">
                <div class="col-xs-12 col-md-3 col-sm-3">

                    <div class="card-header">
                        <h2>Last actions</h2>
                    </div>

                    <div style="padding: 10px">
                        <div class="col-xs-6 col-md-6 col-sm-6" style="padding:0">
                            <div class="f-500 c-green">APPROVED</div>
                            <div id="lastOrderApproved" class="c-green numbers">#</div>

                            <div class="f-500 c-brown">DECLINED</div>
                            <div id="lastOrderDeclined" class=" c-brown numbers">#</div>

                        </div>
                        <div class="col-xs-6 col-md-6 col-sm-6" style="padding:0">
                            <div class="f-500 c-cyan">ANALYSING</div>
                            <div id="lastOrderAnalysing" class="c-cyan numbers">#</div>

                            <div class="f-500 c-red">CANCELED</div>
                            <div id="lastOrderCanceled" class="c-red numbers">#</div>
                        </div>
                    </div>

                </div>
                <div id="lastorders" class="col-xs-12 col-md-9 col-sm-9" style="padding:0">

                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                 <div class="card">
                        <div class="card-header">
                            <h2>submit total and approvals (US$)</h2>
                        </div>
                        <div class="card-body">
                            <div class="chart-edge">
                                <div id="curved-line-chart" class="flot-chart"></div>
                                <div class="flc-chart-edge"></div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php else : ?>
 <div class="container">
    <div class="block-header">
        <h2>The ClearSale Total module is disabled.</h2>
	<br />
	<span>Please, verify the module configuration at System>Configuration>ClearSale>Total.</span>
     </div>
</div>
<?php endif; ?>
